VAGAS_EXEMPLO = [
    {
        "cargo": "Entregador", "empresa": "Mercado Livre", "cidade": "Rio de Janeiro", "estado": "RJ",
        "salario": 2800, "modalidade": "Presencial", "veiculo": "Moto", "categoria": "Entregador",
        "descricao": "Realizar entregas de encomendas na zona sul do Rio de Janeiro.",
        "beneficios": "Vale alimentação, vale transporte, seguro de vida",
        "requisitos": "CNH categoria A, moto própria, disponibilidade integral",
    },
    {
        "cargo": "Motorista", "empresa": "Shopee Express", "cidade": "Niterói", "estado": "RJ",
        "salario": 3500, "modalidade": "Presencial", "veiculo": "Van", "categoria": "Motorista",
        "descricao": "Transporte de cargas entre centros de distribuição da região metropolitana.",
        "beneficios": "Vale alimentação, plano de saúde, participação nos lucros",
        "requisitos": "CNH categoria D, experiência mínima de 2 anos",
    },
    {
        "cargo": "Auxiliar Logístico", "empresa": "Loggi", "cidade": "São Gonçalo", "estado": "RJ",
        "salario": 2600, "modalidade": "Presencial", "veiculo": None, "categoria": "Auxiliar Logístico",
        "descricao": "Apoio nas operações de separação e conferência de encomendas.",
        "beneficios": "Vale alimentação, vale transporte",
        "requisitos": "Ensino médio completo, disponibilidade de horário",
    },
    {
        "cargo": "Motorista Caminhoneiro", "empresa": "JadLog", "cidade": "Campinas", "estado": "SP",
        "salario": 4200, "modalidade": "Presencial", "veiculo": "Caminhão", "categoria": "Caminhoneiro",
        "descricao": "Transporte de cargas em rotas interestaduais entre São Paulo e Minas Gerais.",
        "beneficios": "Diária, vale alimentação, seguro de vida, plano odontológico",
        "requisitos": "CNH categoria E, curso MOPP, experiência com carga fracionada",
    },
    {
        "cargo": "Conferente", "empresa": "Total Express", "cidade": "Guarulhos", "estado": "SP",
        "salario": 2450, "modalidade": "Presencial", "veiculo": None, "categoria": "Conferente",
        "descricao": "Conferência de mercadorias na entrada e saída do centro de distribuição.",
        "beneficios": "Vale alimentação, vale transporte, plano de saúde",
        "requisitos": "Ensino médio completo, experiência em conferência de estoque",
    },
    {
        "cargo": "Estoquista", "empresa": "Amazon", "cidade": "Cajamar", "estado": "SP",
        "salario": 2700, "modalidade": "Presencial", "veiculo": None, "categoria": "Estoquista",
        "descricao": "Organização e reposição de produtos no centro de distribuição.",
        "beneficios": "Vale alimentação, plano de saúde, plano odontológico",
        "requisitos": "Ensino médio completo, disponibilidade para turnos",
    },
    {
        "cargo": "Operador de Empilhadeira", "empresa": "DHL Supply Chain", "cidade": "Barueri", "estado": "SP",
        "salario": 3100, "modalidade": "Presencial", "veiculo": "Empilhadeira", "categoria": "Operador",
        "descricao": "Movimentação de cargas paletizadas dentro do armazém.",
        "beneficios": "Vale alimentação, vale transporte, seguro de vida",
        "requisitos": "Certificado de operador de empilhadeira, experiência mínima de 1 ano",
    },
    {
        "cargo": "Motoboy", "empresa": "iFood", "cidade": "Belo Horizonte", "estado": "MG",
        "salario": 2500, "modalidade": "Autônomo", "veiculo": "Moto", "categoria": "Motoboy",
        "descricao": "Entregas de pedidos de restaurantes parceiros na região central.",
        "beneficios": "Bônus por produtividade, seguro contra acidentes",
        "requisitos": "Moto própria, CNH categoria A, smartphone",
    },
    {
        "cargo": "Supervisor de Logística", "empresa": "Sequoia Logística", "cidade": "Curitiba", "estado": "PR",
        "salario": 5800, "modalidade": "Presencial", "veiculo": None, "categoria": "Supervisor",
        "descricao": "Gestão da equipe de expedição e acompanhamento de indicadores de performance.",
        "beneficios": "Vale alimentação, plano de saúde, plano odontológico, bônus anual",
        "requisitos": "Superior completo em Logística ou áreas afins, experiência em gestão de equipes",
    },
    {
        "cargo": "Coordenador de Transportes", "empresa": "Rappi", "cidade": "Porto Alegre", "estado": "RS",
        "salario": 6200, "modalidade": "Híbrido", "veiculo": None, "categoria": "Coordenador",
        "descricao": "Coordenação da malha de entregadores parceiros na região sul.",
        "beneficios": "Vale alimentação, plano de saúde, day off no aniversário",
        "requisitos": "Superior completo, experiência com gestão de última milha",
    },
    {
        "cargo": "Analista de Logística", "empresa": "Magazine Luiza", "cidade": "Franca", "estado": "SP",
        "salario": 4300, "modalidade": "Híbrido", "veiculo": None, "categoria": "Analista",
        "descricao": "Análise de indicadores de frete e otimização de rotas de entrega.",
        "beneficios": "Vale alimentação, plano de saúde, participação nos lucros",
        "requisitos": "Superior completo em Logística, Administração ou Engenharia, Excel avançado",
    },
    {
        "cargo": "Gestor de Operações", "empresa": "Correios", "cidade": "Brasília", "estado": "DF",
        "salario": 7500, "modalidade": "Presencial", "veiculo": None, "categoria": "Gestor",
        "descricao": "Gestão das operações de triagem e distribuição de encomendas do Distrito Federal.",
        "beneficios": "Vale alimentação, plano de saúde, plano odontológico, previdência privada",
        "requisitos": "Superior completo, experiência mínima de 5 anos em gestão logística",
    },
    {
        "cargo": "Entregador", "empresa": "Uber Eats", "cidade": "Salvador", "estado": "BA",
        "salario": 2400, "modalidade": "Autônomo", "veiculo": "Bicicleta", "categoria": "Entregador",
        "descricao": "Entregas de pedidos na região central de Salvador.",
        "beneficios": "Flexibilidade de horários, bônus por avaliação",
        "requisitos": "Bicicleta própria, smartphone, disponibilidade de horário",
    },
    {
        "cargo": "Motorista", "empresa": "FedEx", "cidade": "Recife", "estado": "PE",
        "salario": 3700, "modalidade": "Presencial", "veiculo": "Van", "categoria": "Motorista",
        "descricao": "Entrega de encomendas expressas na região metropolitana do Recife.",
        "beneficios": "Vale alimentação, plano de saúde, seguro de vida",
        "requisitos": "CNH categoria B ou D, experiência com entregas expressas",
    },
    {
        "cargo": "Auxiliar de Estoque", "empresa": "Carrefour", "cidade": "Fortaleza", "estado": "CE",
        "salario": 2300, "modalidade": "Presencial", "veiculo": None, "categoria": "Auxiliar Logístico",
        "descricao": "Recebimento e organização de mercadorias no centro de distribuição.",
        "beneficios": "Vale alimentação, vale transporte, desconto em compras",
        "requisitos": "Ensino médio completo, disponibilidade para turnos",
    },
    {
        "cargo": "Motorista Entregador", "empresa": "Magalu Entregas", "cidade": "Manaus", "estado": "AM",
        "salario": 3200, "modalidade": "Presencial", "veiculo": "Furgão", "categoria": "Motorista",
        "descricao": "Distribuição de encomendas de e-commerce na capital amazonense.",
        "beneficios": "Vale alimentação, vale combustível, seguro de vida",
        "requisitos": "CNH categoria B, experiência com direção defensiva",
    },
    {
        "cargo": "Conferente de Cargas", "empresa": "Braspress", "cidade": "Contagem", "estado": "MG",
        "salario": 2550, "modalidade": "Presencial", "veiculo": None, "categoria": "Conferente",
        "descricao": "Conferência e etiquetagem de cargas fracionadas.",
        "beneficios": "Vale alimentação, vale transporte, plano de saúde",
        "requisitos": "Ensino médio completo, experiência em transportadoras",
    },
    {
        "cargo": "Operador de Empilhadeira", "empresa": "Ambev Logística", "cidade": "Sorocaba", "estado": "SP",
        "salario": 3300, "modalidade": "Presencial", "veiculo": "Empilhadeira", "categoria": "Operador",
        "descricao": "Movimentação de pallets no centro de distribuição de bebidas.",
        "beneficios": "Vale alimentação, plano de saúde, participação nos lucros",
        "requisitos": "Certificado de operador de empilhadeira, disponibilidade para turnos",
    },
    {
        "cargo": "Motociclista Entregador", "empresa": "Loggi", "cidade": "Goiânia", "estado": "GO",
        "salario": 2650, "modalidade": "Presencial", "veiculo": "Moto", "categoria": "Motoboy",
        "descricao": "Entregas de encomendas de e-commerce na região metropolitana de Goiânia.",
        "beneficios": "Vale alimentação, seguro contra acidentes",
        "requisitos": "CNH categoria A, moto própria",
    },
    {
        "cargo": "Analista de Transportes", "empresa": "Localiza Log", "cidade": "Belo Horizonte", "estado": "MG",
        "salario": 4600, "modalidade": "Híbrido", "veiculo": None, "categoria": "Analista",
        "descricao": "Planejamento de rotas e negociação com transportadoras parceiras.",
        "beneficios": "Vale alimentação, plano de saúde, plano odontológico",
        "requisitos": "Superior completo, conhecimento em roteirização",
    },
    {
        "cargo": "Auxiliar de Expedição", "empresa": "Natura", "cidade": "Cajamar", "estado": "SP",
        "salario": 2500, "modalidade": "Presencial", "veiculo": None, "categoria": "Auxiliar Logístico",
        "descricao": "Separação e embalagem de pedidos para expedição.",
        "beneficios": "Vale alimentação, vale transporte, desconto em produtos",
        "requisitos": "Ensino médio completo, atenção a detalhes",
    },
    {
        "cargo": "Motorista Carreteiro", "empresa": "Rodonaves", "cidade": "Ribeirão Preto", "estado": "SP",
        "salario": 4800, "modalidade": "Presencial", "veiculo": "Carreta", "categoria": "Caminhoneiro",
        "descricao": "Transporte de cargas em rotas de longa distância pelo interior de São Paulo.",
        "beneficios": "Diária, vale alimentação, seguro de vida, curso de reciclagem pago",
        "requisitos": "CNH categoria E, curso MOPP, experiência com carreta",
    },
    {
        "cargo": "Supervisor de Armazém", "empresa": "GPA Log", "cidade": "Osasco", "estado": "SP",
        "salario": 5500, "modalidade": "Presencial", "veiculo": None, "categoria": "Supervisor",
        "descricao": "Supervisão das operações de recebimento, armazenagem e expedição.",
        "beneficios": "Vale alimentação, plano de saúde, plano odontológico, bônus por metas",
        "requisitos": "Superior completo ou cursando, experiência em gestão de armazém",
    },
    {
        "cargo": "Entregador de Bicicleta", "empresa": "Rappi", "cidade": "Florianópolis", "estado": "SC",
        "salario": 2200, "modalidade": "Autônomo", "veiculo": "Bicicleta", "categoria": "Entregador",
        "descricao": "Entregas rápidas na região central de Florianópolis.",
        "beneficios": "Flexibilidade de horários, bônus por avaliação",
        "requisitos": "Bicicleta própria, smartphone",
    },
    {
        "cargo": "Motorista Rural", "empresa": "Correios", "cidade": "Rio Branco", "estado": "AC",
        "salario": 3400, "modalidade": "Presencial", "veiculo": "Caminhão", "categoria": "Motorista",
        "descricao": "Transporte de encomendas entre Rio Branco e municípios do interior do Acre.",
        "beneficios": "Vale alimentação, plano de saúde, previdência privada",
        "requisitos": "CNH categoria D, disponibilidade para viagens regionais",
    },
    {
        "cargo": "Entregador", "empresa": "JadLog", "cidade": "Maceió", "estado": "AL",
        "salario": 2500, "modalidade": "Presencial", "veiculo": "Moto", "categoria": "Entregador",
        "descricao": "Entregas de encomendas na região metropolitana de Maceió.",
        "beneficios": "Vale alimentação, vale transporte",
        "requisitos": "CNH categoria A, moto própria",
    },
    {
        "cargo": "Auxiliar Logístico", "empresa": "Correios", "cidade": "Macapá", "estado": "AP",
        "salario": 2350, "modalidade": "Presencial", "veiculo": None, "categoria": "Auxiliar Logístico",
        "descricao": "Apoio na triagem e distribuição de encomendas em Macapá.",
        "beneficios": "Vale alimentação, plano de saúde",
        "requisitos": "Ensino médio completo, disponibilidade de horário",
    },
    {
        "cargo": "Operador de Empilhadeira", "empresa": "Vale Logística", "cidade": "Vitória", "estado": "ES",
        "salario": 3600, "modalidade": "Presencial", "veiculo": "Empilhadeira", "categoria": "Operador",
        "descricao": "Movimentação de cargas no terminal portuário de Vitória.",
        "beneficios": "Vale alimentação, plano de saúde, plano odontológico, participação nos lucros",
        "requisitos": "Certificado de operador de empilhadeira, experiência em operações portuárias",
    },
    {
        "cargo": "Motorista Carreteiro", "empresa": "Suzano Logística", "cidade": "São Luís", "estado": "MA",
        "salario": 4400, "modalidade": "Presencial", "veiculo": "Carreta", "categoria": "Caminhoneiro",
        "descricao": "Transporte de celulose entre unidades industriais e o porto de São Luís.",
        "beneficios": "Diária, vale alimentação, seguro de vida",
        "requisitos": "CNH categoria E, curso MOPP, experiência com carga pesada",
    },
    {
        "cargo": "Conferente", "empresa": "JBS Logística", "cidade": "Cuiabá", "estado": "MT",
        "salario": 2700, "modalidade": "Presencial", "veiculo": None, "categoria": "Conferente",
        "descricao": "Conferência de cargas refrigeradas no centro de distribuição de Cuiabá.",
        "beneficios": "Vale alimentação, vale transporte, plano de saúde",
        "requisitos": "Ensino médio completo, experiência com logística de frios",
    },
    {
        "cargo": "Auxiliar Logístico", "empresa": "BRF Logística", "cidade": "Campo Grande", "estado": "MS",
        "salario": 2400, "modalidade": "Presencial", "veiculo": None, "categoria": "Auxiliar Logístico",
        "descricao": "Apoio nas operações de armazenagem do centro de distribuição de alimentos.",
        "beneficios": "Vale alimentação, vale transporte",
        "requisitos": "Ensino médio completo, disponibilidade para turnos",
    },
    {
        "cargo": "Motoboy", "empresa": "Correios", "cidade": "Belém", "estado": "PA",
        "salario": 2450, "modalidade": "Presencial", "veiculo": "Moto", "categoria": "Motoboy",
        "descricao": "Entregas expressas na região metropolitana de Belém.",
        "beneficios": "Vale alimentação, plano de saúde",
        "requisitos": "CNH categoria A, moto própria",
    },
    {
        "cargo": "Estoquista", "empresa": "Magazine Luiza", "cidade": "João Pessoa", "estado": "PB",
        "salario": 2350, "modalidade": "Presencial", "veiculo": None, "categoria": "Estoquista",
        "descricao": "Organização e controle de estoque no centro de distribuição regional.",
        "beneficios": "Vale alimentação, vale transporte, desconto em compras",
        "requisitos": "Ensino médio completo, disponibilidade de horário",
    },
    {
        "cargo": "Entregador", "empresa": "Total Express", "cidade": "Teresina", "estado": "PI",
        "salario": 2300, "modalidade": "Presencial", "veiculo": "Moto", "categoria": "Entregador",
        "descricao": "Entregas de encomendas de e-commerce na capital piauiense.",
        "beneficios": "Vale alimentação, vale transporte",
        "requisitos": "CNH categoria A, moto própria",
    },
    {
        "cargo": "Motorista", "empresa": "Azul Cargo Express", "cidade": "Natal", "estado": "RN",
        "salario": 3600, "modalidade": "Presencial", "veiculo": "Van", "categoria": "Motorista",
        "descricao": "Transporte de cargas aéreas entre o aeroporto e centros de distribuição de Natal.",
        "beneficios": "Vale alimentação, plano de saúde, seguro de vida",
        "requisitos": "CNH categoria B ou D, experiência com cargas expressas",
    },
    {
        "cargo": "Auxiliar Logístico", "empresa": "JadLog", "cidade": "Porto Velho", "estado": "RO",
        "salario": 2500, "modalidade": "Presencial", "veiculo": None, "categoria": "Auxiliar Logístico",
        "descricao": "Apoio na separação e conferência de encomendas em Porto Velho.",
        "beneficios": "Vale alimentação, vale transporte",
        "requisitos": "Ensino médio completo, disponibilidade de horário",
    },
    {
        "cargo": "Entregador", "empresa": "Correios", "cidade": "Boa Vista", "estado": "RR",
        "salario": 2400, "modalidade": "Presencial", "veiculo": "Moto", "categoria": "Entregador",
        "descricao": "Entregas de encomendas na região central de Boa Vista.",
        "beneficios": "Vale alimentação, plano de saúde",
        "requisitos": "CNH categoria A, moto própria",
    },
    {
        "cargo": "Operador de Empilhadeira", "empresa": "Nestlé Logística", "cidade": "Aracaju", "estado": "SE",
        "salario": 3200, "modalidade": "Presencial", "veiculo": "Empilhadeira", "categoria": "Operador",
        "descricao": "Movimentação de cargas paletizadas no centro de distribuição de alimentos.",
        "beneficios": "Vale alimentação, plano de saúde, plano odontológico",
        "requisitos": "Certificado de operador de empilhadeira, disponibilidade para turnos",
    },
    {
        "cargo": "Motorista Carreteiro", "empresa": "Rodonaves", "cidade": "Palmas", "estado": "TO",
        "salario": 4300, "modalidade": "Presencial", "veiculo": "Carreta", "categoria": "Caminhoneiro",
        "descricao": "Transporte de cargas em rotas entre Tocantins e o Centro-Oeste.",
        "beneficios": "Diária, vale alimentação, seguro de vida",
        "requisitos": "CNH categoria E, curso MOPP, experiência com carreta",
    },
]
